---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapi-deployment
  template:
    metadata:
      labels:
        app: flaskapi-deployment
    spec:
      containers:
        - name: flaskapi
          image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj27/flaskapi
          ports:
            - containerPort: 8081
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
          envFrom:
            - configMapRef:
                name: mysql-config
