apiVersion: v1
kind: Service
metadata:
 creationTimestamp: null
 labels:
  app: flaskapi-deployment
 name: flaskapi-svc
spec:
 ports:
 - port: 8080
   protocol: TCP
   targetPort: 8081
 selector:
  app: flaskapi-deployment
 type: ClusterIP
status:
 loadBalancer: {}
