apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: flaskapi-deployment
  name: flaskapi-rte
spec:
  host: ""
  port:
    targetPort: 8081
  to:
    kind: ""
    name: flaskapi-svc
    weight: null
status:
