apiVersion: v1
kind: Service
metadata:
 creationTimestamp: null
 labels:
  app: db
 name: mysql
spec:
 ports:
 - port: 3307
   protocol: TCP
   targetPort: 3306
 selector:
  app: db
 type: ClusterIP
status:
 loadBalancer: {}
