apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
 accessModes:
  - ReadWriteMany
 volumeMode: Filesystem
 resources:
  requests:
   storage: 1Gi
 storageClassName: managed-nfs-storage
